#!/bin/bash
gcc -std=gnu99  -o enc_server enc_server.c otp_server.c otp_common.c
gcc -std=gnu99  -o enc_client enc_client.c otp_client.c otp_common.c
gcc -std=gnu99  -o dec_server dec_server.c otp_server.c otp_common.c
gcc -std=gnu99  -o dec_client dec_client.c otp_client.c otp_common.c
gcc -std=gnu99  -o keygen keygen.c
